@startuml qmp_diagrama

class Prenda {
    Color colorPrimario
    Optional<Color> colorSecundario
}

class Tela

Prenda --> "1" Tela

enum Trama
enum Material

Tela --> "1" Trama
Tela --> "1" Material

enum TipoPrenda {
    CategoriaPrenda categoria
}

Prenda --> "1" TipoPrenda

enum CategoriaPrenda

TipoPrenda --> "1" CategoriaPrenda

@enduml